# -*- coding: utf-8 -*-
"""Bokeh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p-QXpzOj3h5Jpnvyoq0HDHZsThEqxESy
"""

!pip install openbb

from openbb_terminal.sdk import openbb

from bokeh.plotting import figure, show, output_notebook
from bokeh.models import ColumnDataSource

# Fetch data
data = openbb.stocks.load(symbol = 'AAPL')

start_date = '2023-09-01'
filtered_data = data[start_date:]

# Prepare data for Bokeh
source = ColumnDataSource(data={
    'date': filtered_data.index,
    'open': filtered_data['Open'],
    'close': filtered_data['Close'],
    'high': filtered_data['High'],
    'low': filtered_data['Low']
})

# Create the candlestick chart
p = figure(x_axis_type="datetime", width=1000, height=400, title="AAPL Candlestick Chart for September 1st 2023 onwards")
p.grid.grid_line_alpha = 0.3

# Define segments for high and low
p.segment('date', 'high', 'date', 'low', color="black", source=source)

# Define vbars for open and close prices
p.vbar('date', 12*60*60*1000, 'open', 'close', fill_color="green", line_color="black", source=source, legend_label="Price Rise")
p.vbar('date', 12*60*60*1000, 'close', 'open', fill_color="red", line_color="black", source=source, legend_label="Price Drop")

# Display
output_notebook()
show(p)

